// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231101080904_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-rc.2.23480.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Activity", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("ActivityId")
                        .HasColumnType("text");

                    b.Property<Geometry>("BoundingBox")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalTimerTime")
                        .HasColumnType("numeric");

                    b.HasKey("UserId", "ActivityId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Core.Lap", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("ActivityId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Ascent")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CadenceAverage")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CadenceMax")
                        .HasColumnType("numeric");

                    b.Property<uint?>("Calories")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Descent")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Distance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Duration")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DurationActive")
                        .HasColumnType("numeric");

                    b.Property<Point>("EndPosition")
                        .HasColumnType("geometry (point)");

                    b.Property<uint?>("HeartRateAverage")
                        .HasColumnType("bigint");

                    b.Property<uint?>("HeartRateMax")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("PowerAverage")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PowerMax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SpeedAverage")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SpeedMax")
                        .HasColumnType("numeric");

                    b.Property<Point>("StartPosition")
                        .HasColumnType("geometry (point)");

                    b.HasKey("UserId", "ActivityId", "StartTime");

                    b.ToTable("Lap");
                });

            modelBuilder.Entity("Core.Record", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("ActivityId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Altitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Cadence")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Distance")
                        .HasColumnType("numeric");

                    b.Property<uint?>("HeartRate")
                        .HasColumnType("bigint");

                    b.Property<Point>("Position")
                        .HasColumnType("geometry (point)");

                    b.Property<decimal?>("Power")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Speed")
                        .HasColumnType("numeric");

                    b.HasKey("UserId", "ActivityId", "Timestamp");

                    b.ToTable("Record");
                });

            modelBuilder.Entity("Core.Session", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("ActivityId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Ascent")
                        .HasColumnType("numeric");

                    b.Property<Geometry>("BoundingBox")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<decimal?>("CadenceAverage")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CadenceMax")
                        .HasColumnType("numeric");

                    b.Property<uint?>("Calories")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Descent")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Distance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Duration")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DurationActive")
                        .HasColumnType("numeric");

                    b.Property<uint?>("HeartRateAverage")
                        .HasColumnType("bigint");

                    b.Property<uint?>("HeartRateMax")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("PowerAverage")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PowerMax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SpeedAverage")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SpeedMax")
                        .HasColumnType("numeric");

                    b.HasKey("UserId", "ActivityId", "StartTime");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("Core.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Picture")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UserUser", b =>
                {
                    b.Property<string>("FollowersUserId")
                        .HasColumnType("text");

                    b.Property<string>("FollowingUserId")
                        .HasColumnType("text");

                    b.HasKey("FollowersUserId", "FollowingUserId");

                    b.HasIndex("FollowingUserId");

                    b.ToTable("Followers", (string)null);
                });

            modelBuilder.Entity("Core.Activity", b =>
                {
                    b.HasOne("Core.User", null)
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Lap", b =>
                {
                    b.HasOne("Core.Activity", null)
                        .WithMany("Laps")
                        .HasForeignKey("UserId", "ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Record", b =>
                {
                    b.HasOne("Core.Activity", null)
                        .WithMany("Records")
                        .HasForeignKey("UserId", "ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Session", b =>
                {
                    b.HasOne("Core.Activity", null)
                        .WithMany("Sessions")
                        .HasForeignKey("UserId", "ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserUser", b =>
                {
                    b.HasOne("Core.User", null)
                        .WithMany()
                        .HasForeignKey("FollowersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.User", null)
                        .WithMany()
                        .HasForeignKey("FollowingUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Activity", b =>
                {
                    b.Navigation("Laps");

                    b.Navigation("Records");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Core.User", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
