name: Checks (backend)

on:
  pull_request:
    branches:
      - main
    paths:
      - backend/
      - flake.*

defaults:
  run:
    working-directory: ./backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Build backend package
      run: nix build .#backend -L

  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Format
      run: nix develop .#backend --command dotnet format --verify-no-changes
