name: Checks (frontend)

on:
  pull_request:
    branches:
      - main
    paths:
      - frontend/**
      - flake.*
      - .github/workflows/checks.frontend.yml

defaults:
  run:
    working-directory: ./frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: tf-viewer
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build frontend package
        run: nix build .#frontend -L

  type-check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: tf-viewer
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix develop .#frontend --command npm ci
      - name: Sync types
        run: |
          nix develop .#frontend --command npx svelte-kit sync
          nix develop .#frontend --command npx houdini generate
      - name: Check types
        run: nix develop .#frontend --command npx svelte-check --tsconfig ./tsconfig.json

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: tf-viewer
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix develop .#frontend --command npm ci
      - name: Format
        run: nix develop .#frontend --command npx prettier --check .

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: tf-viewer
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix develop .#frontend --command npm ci
      - name: Lint
        run: nix develop .#frontend --command npx eslint .
