name: Checks

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Build server
      run: nix build .#server -L

  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Format
      run: nix develop --command dotnet format --verify-no-changes
