name: Checks (backend)

on:
  pull_request:
    branches:
      - main
    paths:
      - backend/**
      - flake.*
      - .github/workflows/checks.backend.yml

defaults:
  run:
    working-directory: ./backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
    - uses: cachix/cachix-action@v14
      with:
        name: tf-viewer
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build backend package
      run: nix build .#backend -L

  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
    - uses: cachix/cachix-action@v14
      with:
        name: tf-viewer
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Format
      run: nix develop .#backend --command dotnet format --verify-no-changes
