name: Build and publish

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
    - uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Build server
      run: nix build .#server -L

    - name: Build OCI image
      run: nix build .#image -L

    - uses: actions/upload-artifact@v3
      with:
        name: oci-image
        path: result

  publish:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: oci-image

    - name: Authenticate with registry
      run: |
        skopeo login ${{ env.REGISTRY }} --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

    - name: Copy image to registry
      run: |
        skopeo copy docker-archive:result docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
