name: Build and publish (backend)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - backend/
      - flake.*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: tf-viewer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
    - uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Build backend package
      run: nix build .#backend -L

    - name: Build OCI image
      run: nix build .#backend-image -L

    - uses: actions/upload-artifact@v3
      with:
        name: oci-image
        path: result

  publish:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: oci-image

    - name: Authenticate with registry
      run: |
        skopeo login ${{ env.REGISTRY }} --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

    - name: Copy image to registry
      run: |
        skopeo copy docker-archive:result docker://${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
