name: Build and publish (backend)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - backend/**
      - flake.*
      - .github/workflows/publish.backend.yml

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: tf-viewer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
    - uses: cachix/cachix-action@v14
      with:
        name: tf-viewer
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build backend package
      run: nix build .#backend -L

    - name: Build OCI image
      run: nix build .#backend-image -L

    - uses: actions/upload-artifact@v4
      with:
        name: oci-image
        path: result

  publish:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: oci-image

    - name: Authenticate with registry
      run: |
        skopeo login ${{ env.REGISTRY }} --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

    - name: Copy image to registry
      run: |
        skopeo copy docker-archive:result docker://${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
